### 1. Pandas 데이터분석 기초

1. pandas user Guide : 10 minutes to pandas
https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html

2. Pandas 10분 완성(데잇걸즈)
https://dataitgirls2.github.io/10minutes2pandas/

3. Pandas Cheat sheet
https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

4. 점프투파이썬
https://wikidocs.net/11

## [ 10 minutes to pandas ]

In [54]:
import numpy as np
import pandas as pd

### 1. Object creation

In [55]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [59]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [60]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [61]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [7]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [62]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [63]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [64]:
df2.values

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [8]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [ ]:
## Pandas cheat sheet 참고

### 2. Viewing data

In [65]:
df = pd.read_csv('02.dataset.csv', encoding = 'euc-kr')

In [66]:
df.head()

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
0,378508,378475,508475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,378509,378475,509475,2021-01-01,0.00,0.00,0.4,0.00,0.27,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,378510,378475,510475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,378511,378475,511475,2021-01-01,0.08,0.08,0.2,0.39,0.16,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,378512,378475,512475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df.tail()

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
302163,417521,417475,521475,2021-12-30,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302164,418517,418475,517475,2021-12-30,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302165,418518,418475,518475,2021-12-30,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302166,418519,418475,519475,2021-12-30,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302167,418520,418475,520475,2021-12-30,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [67]:
df.index

RangeIndex(start=0, stop=302168, step=1)

In [20]:
df.columns

Index(['GRID_ID', 'GRID_X_AXIS', 'GRID_Y_AXIS', 'OCRN_YMD', 'M00', 'M10',
       'M15', 'M20', 'M25', 'M30', 'M35', 'M40', 'M45', 'M50', 'M55', 'M60',
       'M65', 'M70', 'F00', 'F10', 'F15', 'F20', 'F25', 'F30', 'F35', 'F40',
       'F45', 'F50', 'F55', 'F60', 'F65', 'F70', 'DONG_CD', 'DONG_NM',
       'HGTPOJ_ACDNT_OCRN_CNT', 'PNTRINJ_OCRN_CNT', 'MCHN_ACDNT_OCRN_CNT',
       'ETC_OCRN_CNT', 'BLTRM_OCRN_CNT', 'ACDNT_INJ_OCRN_CNT',
       'EXCL_DISEASE_OCRN_CNT', 'VHC_ACDNT_OCRN_CNT', 'HRFAF_OCRN_CNT',
       'AGRCMCHN_ACDNT_OCRN_CNT', 'DRKNSTAT_OCRN_CNT',
       'ANML_INSCT_ACDNT_OCRN_CNT', 'FLPS_ACDNT_OCRN_CNT', 'UNKNWN_OCRN_CNT',
       'PDST_ACDNT_OCRN_CNT', 'LACRTWND_OCRN_CNT', 'MTRCYC_ACDNT_OCRN_CNT',
       'THML_DAMG_OCRN_CNT', 'DRV_ACDNT_OCRN_CNT', 'DRWNG_OCRN_CNT',
       'PRGNTW_ACDNT_OCRN_CNT', 'BCYC_ACDNT_OCRN_CNT', 'ELTRC_ACDNT_OCRN_CNT',
       'POSNG_OCRN_CNT', 'ASPHYXIA_OCRN_CNT', 'FALLING_OCRN_CNT',
       'FLAME_OCRN_CNT', 'CHMC_SBSTNC_ACDNT_OCRN_CNT', 'WETHR_ACDNT_OCRN_CNT',
       'SXAL_ASALT_OCRN_CNT', 'BURN_OCRN_CNT'],
      dtype='object')

In [21]:
df.values

array([[378508, 378475, 508475, ..., 0.0, 0.0, 0.0],
       [378509, 378475, 509475, ..., 0.0, 0.0, 0.0],
       [378510, 378475, 510475, ..., 0.0, 0.0, 0.0],
       ...,
       [418518, 418475, 518475, ..., 0.0, 0.0, 0.0],
       [418519, 418475, 519475, ..., 0.0, 0.0, 0.0],
       [418520, 418475, 520475, ..., 0.0, 0.0, 0.0]], dtype=object)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302168 entries, 0 to 302167
Data columns (total 65 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   GRID_ID                     302168 non-null  int64
 1   GRID_X_AXIS                 302168 non-null  int64
 2   GRID_Y_AXIS                 302168 non-null  int64
 3   OCRN_YMD                    302168 non-null  object
 4   M00                         302168 non-null  float64
 5   M10                         302168 non-null  float64
 6   M15                         302168 non-null  float64
 7   M20                         302168 non-null  float64
 8   M25                         302168 non-null  float64
 9   M30                         302168 non-null  float64
 10  M35                         302168 non-null  float64
 11  M40                         302168 non-null  float64
 12  M45                         302168 non-null  float64
 13  M50                         302168 non-null  float64
 14  M55                         302168 non-null  float64
 15  M60                         302168 non-null  float64
 16  M65                         302168 non-null  float64
 17  M70                         302168 non-null  float64
 18  F00                         302168 non-null  float64
 19  F10                         302168 non-null  float64
 20  F15                         302168 non-null  float64
 21  F20                         302168 non-null  float64
 22  F25                         302168 non-null  float64
 23  F30                         302168 non-null  float64
 24  F35                         302168 non-null  float64
 25  F40                         302168 non-null  float64
 26  F45                         302168 non-null  float64
 27  F50                         302168 non-null  float64
 28  F55                         302168 non-null  float64
 29  F60                         302168 non-null  float64
 30  F65                         302168 non-null  float64
 31  F70                         302168 non-null  float64
 32  DONG_CD                     302168 non-null  int64
 33  DONG_NM                     302168 non-null  object
 34  HGTPOJ_ACDNT_OCRN_CNT       302168 non-null  float64
 35  PNTRINJ_OCRN_CNT            302168 non-null  float64
 36  MCHN_ACDNT_OCRN_CNT         302168 non-null  float64
 37  ETC_OCRN_CNT                302168 non-null  float64
 38  BLTRM_OCRN_CNT              302168 non-null  float64
 39  ACDNT_INJ_OCRN_CNT          302168 non-null  float64
 40  EXCL_DISEASE_OCRN_CNT       302168 non-null  float64
 41  VHC_ACDNT_OCRN_CNT          302168 non-null  float64
 42  HRFAF_OCRN_CNT              302168 non-null  float64
 43  AGRCMCHN_ACDNT_OCRN_CNT     302168 non-null  float64
 44  DRKNSTAT_OCRN_CNT           302168 non-null  float64
 45  ANML_INSCT_ACDNT_OCRN_CNT   302168 non-null  float64
 46  FLPS_ACDNT_OCRN_CNT         302168 non-null  float64
 47  UNKNWN_OCRN_CNT             302168 non-null  float64
 48  PDST_ACDNT_OCRN_CNT         302168 non-null  float64
 49  LACRTWND_OCRN_CNT           302168 non-null  float64
 50  MTRCYC_ACDNT_OCRN_CNT       302168 non-null  float64
 51  THML_DAMG_OCRN_CNT          302168 non-null  float64
 52  DRV_ACDNT_OCRN_CNT          302168 non-null  float64
 53  DRWNG_OCRN_CNT              302168 non-null  float64
 54  PRGNTW_ACDNT_OCRN_CNT       302168 non-null  float64
 55  BCYC_ACDNT_OCRN_CNT         302168 non-null  float64
 56  ELTRC_ACDNT_OCRN_CNT        302168 non-null  float64
 57  POSNG_OCRN_CNT              302168 non-null  float64
 58  ASPHYXIA_OCRN_CNT           302168 non-null  float64
 59  FALLING_OCRN_CNT            302168 non-null  float64
 60  FLAME_OCRN_CNT              302168 non-null  float64
 61  CHMC_SBSTNC_ACDNT_OCRN_CNT  302168 non-null  float64
 62  WETHR_ACDNT_OCRN_CNT        302168 non-null  float64
 63  SXAL_ASALT_OCRN_CNT         302168 non-null  float64
 64  BURN_OCRN_CNT               302168 non-null  float64
dtypes: float64(59), int64(4), object(2)
memory usage: 149.8+ MB

In [68]:
df.describe()

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,M00,M10,M15,M20,M25,M30,M35,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
count,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,...,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.0,302168.0,302168.000000
mean,393874.438084,393826.635514,523277.570093,18.742905,39.280078,56.934226,108.415764,132.298048,109.834970,106.759611,...,0.000304,0.000003,0.000281,0.000036,0.000248,0.000013,0.000003,0.0,0.0,0.000007
std,9567.726970,9566.993065,9041.045158,101.171821,207.873529,295.132547,521.291677,671.963387,538.590764,519.003592,...,0.017635,0.001819,0.016966,0.006033,0.015753,0.003638,0.001819,0.0,0.0,0.002573
min,378508.000000,378475.000000,505475.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
25%,385534.750000,385475.000000,516475.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
50%,392530.500000,392475.000000,522475.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
75%,401516.250000,401475.000000,530475.000000,0.000000,0.000000,0.050000,0.530000,1.090000,0.820000,1.050000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
max,418520.000000,418475.000000,544475.000000,2530.480000,3186.910000,5969.100000,9616.610000,10751.320000,9515.460000,9995.430000,...,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000

In [70]:
df.describe(include = 'all')

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
count,302168.000000,302168.000000,302168.000000,302168,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,...,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.000000,302168.0,302168.0,302168.000000
unique,NaN,NaN,NaN,353,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,856,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,393874.438084,393826.635514,523277.570093,NaN,18.742905,39.280078,56.934226,108.415764,132.298048,109.834970,...,0.000304,0.000003,0.000281,0.000036,0.000248,0.000013,0.000003,0.0,0.0,0.000007
std,9567.726970,9566.993065,9041.045158,NaN,101.171821,207.873529,295.132547,521.291677,671.963387,538.590764,...,0.017635,0.001819,0.016966,0.006033,0.015753,0.003638,0.001819,0.0,0.0,0.002573
min,378508.000000,378475.000000,505475.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
25%,385534.750000,385475.000000,516475.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
50%,392530.500000,392475.000000,522475.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
75%,401516.250000,401475.000000,530475.000000,NaN,0.000000,0.000000,0.050000,0.530000,1.090000,0.820000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000
max,418520.000000,418475.000000,544475.000000,NaN,2530.480000,3186.910000,5969.100000,9616.610000,10751.320000,9515.460000,...,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,1.000000

In [71]:
df.sort_values(by="GRID_ID")

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
0,378508,378475,508475,2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5136,378508,378475,508475,2021-01-07,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138672,378508,378475,508475,2021-06-17,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
163496,378508,378475,508475,2021-07-17,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
233688,378508,378475,508475,2021-10-10,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237111,418520,418475,520475,2021-10-13,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64199,418520,418475,520475,2021-03-18,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
237967,418520,418475,520475,2021-10-14,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
232831,418520,418475,520475,2021-10-08,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302167,418520,418475,520475,2021-12-30,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
## Pandas cheat sheet 참고

### 3. Selection

In [27]:
df["GRID_ID"]

0         378508
1         378509
2         378510
3         378511
4         378512
           ...
302163    417521
302164    418517
302165    418518
302166    418519
302167    418520
Name: GRID_ID, Length: 302168, dtype: int64

In [72]:
#Rows 
df[100:130]

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
100,382517,382475,517475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101,382518,382475,518475,2021-01-01,0.00,0.00,0.73,16.72,12.51,0.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,382519,382475,519475,2021-01-01,0.00,0.00,0.24,6.84,4.68,0.12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,382520,382475,520475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104,382521,382475,521475,2021-01-01,0.00,0.00,2.96,51.43,204.11,229.71,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105,382522,382475,522475,2021-01-01,0.00,0.00,0.00,10.04,41.95,20.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
106,382523,382475,523475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107,382524,382475,524475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
108,382525,382475,525475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,382526,382475,526475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
110,382527,382475,527475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
111,382528,382475,528475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112,382529,382475,529475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113,382530,382475,530475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
114,382531,382475,531475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
115,382532,382475,532475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
116,382533,382475,533475,2021-01-01,0.28,1.12,0.64,0.00,0.84,0.68,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
117,382534,382475,534475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
118,382535,382475,535475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
119,382537,382475,537475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
120,383505,383475,505475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
121,383506,383475,506475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
122,383507,383475,507475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123,383508,383475,508475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
124,383509,383475,509475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125,383510,383475,510475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126,383511,383475,511475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
127,383512,383475,512475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,383513,383475,513475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
129,383514,383475,514475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [73]:
df.loc[:,'M00':'M30']

         M00   M10  M15   M20   M25   M30
0       0.00  0.00  0.0  0.00  0.00  0.00
1       0.00  0.00  0.4  0.00  0.27  0.22
2       0.00  0.00  0.0  0.00  0.00  0.00
3       0.08  0.08  0.2  0.39  0.16  0.22
4       0.00  0.00  0.0  0.00  0.00  0.00
...      ...   ...  ...   ...   ...   ...
302163  0.00  0.00  0.0  0.00  0.00  0.00
302164  0.00  0.00  0.0  0.00  0.00  0.00
302165  0.00  0.00  0.0  0.00  0.00  0.00
302166  0.00  0.00  0.0  0.00  0.00  0.00
302167  0.00  0.00  0.0  0.00  0.00  0.00

[302168 rows x 6 columns]

In [31]:
df.loc[0:10,'M00':'M30']

     M00   M10  M15   M20   M25   M30
0   0.00  0.00  0.0  0.00  0.00  0.00
1   0.00  0.00  0.4  0.00  0.27  0.22
2   0.00  0.00  0.0  0.00  0.00  0.00
3   0.08  0.08  0.2  0.39  0.16  0.22
4   0.00  0.00  0.0  0.00  0.00  0.00
5   0.00  0.18  0.0  8.30  5.41  1.01
6   0.00  0.00  0.0  0.16  0.17  0.09
7   0.00  0.00  0.0  0.00  0.00  0.00
8   0.00  0.00  0.0  0.00  0.00  0.00
9   0.00  0.00  0.0  0.00  0.00  0.00
10  0.00  0.00  0.0  0.00  0.00  0.00

In [33]:
df.iloc[10]

GRID_ID                           378521
GRID_X_AXIS                       378475
GRID_Y_AXIS                       521475
OCRN_YMD                      2021-01-01
M00                                  0.0
                                 ...
FLAME_OCRN_CNT                       0.0
CHMC_SBSTNC_ACDNT_OCRN_CNT           0.0
WETHR_ACDNT_OCRN_CNT                 0.0
SXAL_ASALT_OCRN_CNT                  0.0
BURN_OCRN_CNT                        0.0
Name: 10, Length: 65, dtype: object

In [34]:
df.iloc[0:10,3:10]

     OCRN_YMD   M00   M10  M15   M20   M25   M30
0  2021-01-01  0.00  0.00  0.0  0.00  0.00  0.00
1  2021-01-01  0.00  0.00  0.4  0.00  0.27  0.22
2  2021-01-01  0.00  0.00  0.0  0.00  0.00  0.00
3  2021-01-01  0.08  0.08  0.2  0.39  0.16  0.22
4  2021-01-01  0.00  0.00  0.0  0.00  0.00  0.00
5  2021-01-01  0.00  0.18  0.0  8.30  5.41  1.01
6  2021-01-01  0.00  0.00  0.0  0.16  0.17  0.09
7  2021-01-01  0.00  0.00  0.0  0.00  0.00  0.00
8  2021-01-01  0.00  0.00  0.0  0.00  0.00  0.00
9  2021-01-01  0.00  0.00  0.0  0.00  0.00  0.00

In [42]:
df.loc[:,'HGTPOJ_ACDNT_OCRN_CNT':'BURN_OCRN_CNT'].sum()

HGTPOJ_ACDNT_OCRN_CNT           4.0
PNTRINJ_OCRN_CNT                1.0
MCHN_ACDNT_OCRN_CNT            27.0
ETC_OCRN_CNT                  111.0
BLTRM_OCRN_CNT                 44.0
ACDNT_INJ_OCRN_CNT            126.0
EXCL_DISEASE_OCRN_CNT         239.0
VHC_ACDNT_OCRN_CNT             28.0
HRFAF_OCRN_CNT                981.0
AGRCMCHN_ACDNT_OCRN_CNT         0.0
DRKNSTAT_OCRN_CNT              58.0
ANML_INSCT_ACDNT_OCRN_CNT      67.0
FLPS_ACDNT_OCRN_CNT           107.0
UNKNWN_OCRN_CNT                 5.0
PDST_ACDNT_OCRN_CNT           158.0
LACRTWND_OCRN_CNT             176.0
MTRCYC_ACDNT_OCRN_CNT         181.0
THML_DAMG_OCRN_CNT              6.0
DRV_ACDNT_OCRN_CNT            216.0
DRWNG_OCRN_CNT                 13.0
PRGNTW_ACDNT_OCRN_CNT           8.0
BCYC_ACDNT_OCRN_CNT            92.0
ELTRC_ACDNT_OCRN_CNT            1.0
POSNG_OCRN_CNT                 85.0
ASPHYXIA_OCRN_CNT              11.0
FALLING_OCRN_CNT               75.0
FLAME_OCRN_CNT                  4.0
CHMC_SBSTNC_ACDNT_OCRN_CNT      1.0
WETHR_ACDNT_OCRN_CNT            0.0
SXAL_ASALT_OCRN_CNT             0.0
BURN_OCRN_CNT                   2.0
dtype: float64

In [77]:
#Boolean indexing
df[df["OCRN_YMD"] == '2021-01-30']

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
24824,378508,378475,508475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24825,378509,378475,509475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24826,378510,378475,510475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24827,378511,378475,511475,2021-01-30,0.06,0.22,0.03,0.20,0.17,0.19,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24828,378512,378475,512475,2021-01-30,0.04,0.09,0.02,0.06,0.06,0.06,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25675,417521,417475,521475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25676,418517,418475,517475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25677,418518,418475,518475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25678,418519,418475,519475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25679,418520,418475,520475,2021-01-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [79]:
df[df["GRID_ID"] > 378510 & df["GRID_ID"] < 378515]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [80]:
df["GRID_ID"] > 378510

0         False
1         False
2         False
3          True
4          True
          ...
302163     True
302164     True
302165     True
302166     True
302167     True
Name: GRID_ID, Length: 302168, dtype: bool

In [57]:
df["GRID_ID"] < 378515

0         False
1         False
2         False
3         False
4         False
          ...
302163     True
302164     True
302165     True
302166     True
302167     True
Name: GRID_ID, Length: 302168, dtype: bool

In [82]:
a = df["GRID_ID"] > 378510
b = df["GRID_ID"] < 378515
c = a*b

In [83]:
df[c]

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
3,378511,378475,511475,2021-01-01,0.08,0.08,0.20,0.39,0.16,0.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,378512,378475,512475,2021-01-01,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,378513,378475,513475,2021-01-01,0.00,0.18,0.00,8.30,5.41,1.01,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,378514,378475,514475,2021-01-01,0.00,0.00,0.00,0.16,0.17,0.09,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
859,378511,378475,511475,2021-01-02,0.09,0.22,0.08,0.35,0.23,0.46,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300462,378514,378475,514475,2021-12-29,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
301315,378511,378475,511475,2021-12-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
301316,378512,378475,512475,2021-12-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
301317,378513,378475,513475,2021-12-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
301318,378514,378475,514475,2021-12-30,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
## Pandas cheat sheet 참고

### 4. Missing data

In [58]:
df.isna()

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
302164,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
302165,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
302166,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
302167,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [59]:
df.isna().sum()

GRID_ID                       0
GRID_X_AXIS                   0
GRID_Y_AXIS                   0
OCRN_YMD                      0
M00                           0
                             ..
FLAME_OCRN_CNT                0
CHMC_SBSTNC_ACDNT_OCRN_CNT    0
WETHR_ACDNT_OCRN_CNT          0
SXAL_ASALT_OCRN_CNT           0
BURN_OCRN_CNT                 0
Length: 65, dtype: int64

In [ ]:
df.dropna(how='any')
df.fillna(value=5)

### 5.Operations

In [84]:
df2 = df.loc[:,'M00':'F70']

In [85]:
df2

,M00,M10,M15,M20,M25,M30,M35,M40,M45,M50,...,F25,F30,F35,F40,F45,F50,F55,F60,F65,F70
0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
1,0.00,0.00,0.4,0.00,0.27,0.22,0.07,0.04,0.44,0.25,...,0.23,0.00,0.37,0.33,0.29,0.04,0.36,0.3,0.0,0.27
2,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
3,0.08,0.08,0.2,0.39,0.16,0.22,0.23,0.27,0.41,0.32,...,0.17,0.13,0.21,0.19,0.21,0.45,0.43,0.3,0.2,0.23
4,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302164,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302165,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302166,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302167,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00

In [90]:
# Stats
df2.mean(axis = 0)

M00     18.742905
M10     39.280078
M15     56.934226
M20    108.415764
M25    132.298048
M30    109.834970
M35    106.759611
M40    105.025826
M45    112.211548
M50    128.807680
M55    116.274220
M60    110.082595
M65     64.983365
M70     76.213202
F00     21.057008
F10     38.905379
F15     53.135823
F20    100.523753
F25    119.510626
F30    100.766220
F35     97.798649
F40    100.493296
F45    116.816047
F50    134.408022
F55    123.307646
F60    100.929957
F65     58.312322
F70     77.566092
dtype: float64

In [ ]:
## Pandas cheat sheet 참고

In [7]:
#Apply
df2.head()

,M00,M10,M15,M20,M25,M30,M35,M40,M45,M50,...,F25,F30,F35,F40,F45,F50,F55,F60,F65,F70
0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
1,0.00,0.00,0.4,0.00,0.27,0.22,0.07,0.04,0.44,0.25,...,0.23,0.00,0.37,0.33,0.29,0.04,0.36,0.3,0.0,0.27
2,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
3,0.08,0.08,0.2,0.39,0.16,0.22,0.23,0.27,0.41,0.32,...,0.17,0.13,0.21,0.19,0.21,0.45,0.43,0.3,0.2,0.23
4,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00

In [91]:
df2.apply(np.cumsum)

,M00,M10,M15,M20,M25,M30,M35,M40,M45,M50,...,F25,F30,F35,F40,F45,F50,F55,F60,F65,F70
0,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.00,0.000000e+00,0.00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.00,0.00,0.00,0.00,0.000000e+00,0.000000e+00
1,0.00,0.000000e+00,4.000000e-01,0.000000e+00,2.700000e-01,2.200000e-01,7.000000e-02,0.04,4.400000e-01,0.25,...,2.300000e-01,0.000000e+00,3.700000e-01,3.300000e-01,0.29,0.04,0.36,0.30,0.000000e+00,2.700000e-01
2,0.00,0.000000e+00,4.000000e-01,0.000000e+00,2.700000e-01,2.200000e-01,7.000000e-02,0.04,4.400000e-01,0.25,...,2.300000e-01,0.000000e+00,3.700000e-01,3.300000e-01,0.29,0.04,0.36,0.30,0.000000e+00,2.700000e-01
3,0.08,8.000000e-02,6.000000e-01,3.900000e-01,4.300000e-01,4.400000e-01,3.000000e-01,0.31,8.500000e-01,0.57,...,4.000000e-01,1.300000e-01,5.800000e-01,5.200000e-01,0.50,0.49,0.79,0.60,2.000000e-01,5.000000e-01
4,0.08,8.000000e-02,6.000000e-01,3.900000e-01,4.300000e-01,4.400000e-01,3.000000e-01,0.31,8.500000e-01,0.57,...,4.000000e-01,1.300000e-01,5.800000e-01,5.200000e-01,0.50,0.49,0.79,0.60,2.000000e-01,5.000000e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,5663506.21,1.186918e+07,1.720370e+07,3.275977e+07,3.997624e+07,3.318861e+07,3.225934e+07,31735443.69,3.390674e+07,38921558.96,...,3.611229e+07,3.044833e+07,2.955162e+07,3.036586e+07,35298071.16,40613803.21,37259624.81,30497803.11,1.762012e+07,2.343799e+07
302164,5663506.21,1.186918e+07,1.720370e+07,3.275977e+07,3.997624e+07,3.318861e+07,3.225934e+07,31735443.69,3.390674e+07,38921558.96,...,3.611229e+07,3.044833e+07,2.955162e+07,3.036586e+07,35298071.16,40613803.21,37259624.81,30497803.11,1.762012e+07,2.343799e+07
302165,5663506.21,1.186918e+07,1.720370e+07,3.275977e+07,3.997624e+07,3.318861e+07,3.225934e+07,31735443.69,3.390674e+07,38921558.96,...,3.611229e+07,3.044833e+07,2.955162e+07,3.036586e+07,35298071.16,40613803.21,37259624.81,30497803.11,1.762012e+07,2.343799e+07
302166,5663506.21,1.186918e+07,1.720370e+07,3.275977e+07,3.997624e+07,3.318861e+07,3.225934e+07,31735443.69,3.390674e+07,38921558.96,...,3.611229e+07,3.044833e+07,2.955162e+07,3.036586e+07,35298071.16,40613803.21,37259624.81,30497803.11,1.762012e+07,2.343799e+07
302167,5663506.21,1.186918e+07,1.720370e+07,3.275977e+07,3.997624e+07,3.318861e+07,3.225934e+07,31735443.69,3.390674e+07,38921558.96,...,3.611229e+07,3.044833e+07,2.955162e+07,3.036586e+07,35298071.16,40613803.21,37259624.81,30497803.11,1.762012e+07,2.343799e+07

In [93]:
df2.apply(lambda x: x.max() - x.min(),axis = 1)

0         0.00
1         0.44
2         0.00
3         0.72
4         0.00
          ...
302163    0.00
302164    0.00
302165    0.00
302166    0.00
302167    0.00
Length: 302168, dtype: float64

In [ ]:
df2.apply(lambda x: x.max() - x.min(), axis =0)

In [ ]:
df2.apply(lambda x: x.max() - x.min(), axis =1)

#### Merge

In [26]:
## Concat
## Pandas cheat sheet 참고

In [94]:
df3 = df.loc[:,'GRID_ID':'OCRN_YMD']

In [95]:
df3.head()

   GRID_ID  GRID_X_AXIS  GRID_Y_AXIS    OCRN_YMD
0   378508       378475       508475  2021-01-01
1   378509       378475       509475  2021-01-01
2   378510       378475       510475  2021-01-01
3   378511       378475       511475  2021-01-01
4   378512       378475       512475  2021-01-01

In [17]:
df3.shape

(302168, 4)

In [19]:
df2.shape

(302168, 28)

In [96]:
pd.concat([df3,df2])

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,F25,F30,F35,F40,F45,F50,F55,F60,F65,F70
0,378508.0,378475.0,508475.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,378509.0,378475.0,509475.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,378510.0,378475.0,510475.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,378511.0,378475.0,511475.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,378512.0,378475.0,512475.0,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302164,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302165,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302166,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302167,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [97]:
pd.concat([df3,df2], axis =1)

,GRID_ID,GRID_X_AXIS,GRID_Y_AXIS,OCRN_YMD,M00,M10,M15,M20,M25,M30,...,F25,F30,F35,F40,F45,F50,F55,F60,F65,F70
0,378508,378475,508475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
1,378509,378475,509475,2021-01-01,0.00,0.00,0.4,0.00,0.27,0.22,...,0.23,0.00,0.37,0.33,0.29,0.04,0.36,0.3,0.0,0.27
2,378510,378475,510475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
3,378511,378475,511475,2021-01-01,0.08,0.08,0.2,0.39,0.16,0.22,...,0.17,0.13,0.21,0.19,0.21,0.45,0.43,0.3,0.2,0.23
4,378512,378475,512475,2021-01-01,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,417521,417475,521475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302164,418517,418475,517475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302165,418518,418475,518475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302166,418519,418475,519475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00
302167,418520,418475,520475,2021-12-30,0.00,0.00,0.0,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00

In [27]:
## Grouping

In [98]:
df.columns

Index(['GRID_ID', 'GRID_X_AXIS', 'GRID_Y_AXIS', 'OCRN_YMD', 'M00', 'M10',
       'M15', 'M20', 'M25', 'M30', 'M35', 'M40', 'M45', 'M50', 'M55', 'M60',
       'M65', 'M70', 'F00', 'F10', 'F15', 'F20', 'F25', 'F30', 'F35', 'F40',
       'F45', 'F50', 'F55', 'F60', 'F65', 'F70', 'DONG_CD', 'DONG_NM',
       'HGTPOJ_ACDNT_OCRN_CNT', 'PNTRINJ_OCRN_CNT', 'MCHN_ACDNT_OCRN_CNT',
       'ETC_OCRN_CNT', 'BLTRM_OCRN_CNT', 'ACDNT_INJ_OCRN_CNT',
       'EXCL_DISEASE_OCRN_CNT', 'VHC_ACDNT_OCRN_CNT', 'HRFAF_OCRN_CNT',
       'AGRCMCHN_ACDNT_OCRN_CNT', 'DRKNSTAT_OCRN_CNT',
       'ANML_INSCT_ACDNT_OCRN_CNT', 'FLPS_ACDNT_OCRN_CNT', 'UNKNWN_OCRN_CNT',
       'PDST_ACDNT_OCRN_CNT', 'LACRTWND_OCRN_CNT', 'MTRCYC_ACDNT_OCRN_CNT',
       'THML_DAMG_OCRN_CNT', 'DRV_ACDNT_OCRN_CNT', 'DRWNG_OCRN_CNT',
       'PRGNTW_ACDNT_OCRN_CNT', 'BCYC_ACDNT_OCRN_CNT', 'ELTRC_ACDNT_OCRN_CNT',
       'POSNG_OCRN_CNT', 'ASPHYXIA_OCRN_CNT', 'FALLING_OCRN_CNT',
       'FLAME_OCRN_CNT', 'CHMC_SBSTNC_ACDNT_OCRN_CNT', 'WETHR_ACDNT_OCRN_CNT',
       'SXAL_ASALT_OCRN_CNT', 'BURN_OCRN_CNT'],
      dtype='object')

In [99]:
df4 = df[['GRID_ID', 'OCRN_YMD',
       'HGTPOJ_ACDNT_OCRN_CNT', 'PNTRINJ_OCRN_CNT', 'MCHN_ACDNT_OCRN_CNT',
       'ETC_OCRN_CNT', 'BLTRM_OCRN_CNT', 'ACDNT_INJ_OCRN_CNT',
       'EXCL_DISEASE_OCRN_CNT', 'VHC_ACDNT_OCRN_CNT', 'HRFAF_OCRN_CNT',
       'AGRCMCHN_ACDNT_OCRN_CNT', 'DRKNSTAT_OCRN_CNT',
       'ANML_INSCT_ACDNT_OCRN_CNT', 'FLPS_ACDNT_OCRN_CNT', 'UNKNWN_OCRN_CNT',
       'PDST_ACDNT_OCRN_CNT', 'LACRTWND_OCRN_CNT', 'MTRCYC_ACDNT_OCRN_CNT',
       'THML_DAMG_OCRN_CNT', 'DRV_ACDNT_OCRN_CNT', 'DRWNG_OCRN_CNT',
       'PRGNTW_ACDNT_OCRN_CNT', 'BCYC_ACDNT_OCRN_CNT', 'ELTRC_ACDNT_OCRN_CNT',
       'POSNG_OCRN_CNT', 'ASPHYXIA_OCRN_CNT', 'FALLING_OCRN_CNT',
       'FLAME_OCRN_CNT', 'CHMC_SBSTNC_ACDNT_OCRN_CNT', 'WETHR_ACDNT_OCRN_CNT',
       'SXAL_ASALT_OCRN_CNT', 'BURN_OCRN_CNT']]

In [100]:
df4.shape

(302168, 33)

In [103]:
df4.head()

,GRID_ID,OCRN_YMD,HGTPOJ_ACDNT_OCRN_CNT,PNTRINJ_OCRN_CNT,MCHN_ACDNT_OCRN_CNT,ETC_OCRN_CNT,BLTRM_OCRN_CNT,ACDNT_INJ_OCRN_CNT,EXCL_DISEASE_OCRN_CNT,VHC_ACDNT_OCRN_CNT,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
0,378508,2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,378509,2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,378510,2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,378511,2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,378512,2021-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [105]:
df4.groupby('OCRN_YMD').sum()

,GRID_ID,HGTPOJ_ACDNT_OCRN_CNT,PNTRINJ_OCRN_CNT,MCHN_ACDNT_OCRN_CNT,ETC_OCRN_CNT,BLTRM_OCRN_CNT,ACDNT_INJ_OCRN_CNT,EXCL_DISEASE_OCRN_CNT,VHC_ACDNT_OCRN_CNT,HRFAF_OCRN_CNT,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
OCRN_YMD,,,,,,,,,,,,,,,,,,,,,
2021-01-01,337156519,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-02,337156519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2021-01-03,337156519,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-04,337156519,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-01-05,337156519,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-26,337156519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-12-27,337156519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-12-28,337156519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-12-29,337156519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021-12-30,337156519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [106]:
df4.groupby(['OCRN_YMD','GRID_ID']).sum()

                    HGTPOJ_ACDNT_OCRN_CNT  PNTRINJ_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                     0.0               0.0
           378509                     0.0               0.0
           378510                     0.0               0.0
           378511                     0.0               0.0
           378512                     0.0               0.0
...                                   ...               ...
2021-12-30 417521                     0.0               0.0
           418517                     0.0               0.0
           418518                     0.0               0.0
           418519                     0.0               0.0
           418520                     0.0               0.0

                    MCHN_ACDNT_OCRN_CNT  ETC_OCRN_CNT  BLTRM_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                   0.0           0.0             0.0
           378509                   0.0           0.0             0.0
           378510                   0.0           0.0             0.0
           378511                   0.0           0.0             0.0
           378512                   0.0           0.0             0.0
...                                 ...           ...             ...
2021-12-30 417521                   0.0           0.0             0.0
           418517                   0.0           0.0             0.0
           418518                   0.0           0.0             0.0
           418519                   0.0           0.0             0.0
           418520                   0.0           0.0             0.0

                    ACDNT_INJ_OCRN_CNT  EXCL_DISEASE_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                  0.0                    0.0
           378509                  0.0                    0.0
           378510                  0.0                    0.0
           378511                  0.0                    0.0
           378512                  0.0                    0.0
...                                ...                    ...
2021-12-30 417521                  0.0                    0.0
           418517                  0.0                    0.0
           418518                  0.0                    0.0
           418519                  0.0                    0.0
           418520                  0.0                    0.0

                    VHC_ACDNT_OCRN_CNT  HRFAF_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                  0.0             0.0
           378509                  0.0             0.0
           378510                  0.0             0.0
           378511                  0.0             0.0
           378512                  0.0             0.0
...                                ...             ...
2021-12-30 417521                  0.0             0.0
           418517                  0.0             0.0
           418518                  0.0             0.0
           418519                  0.0             0.0
           418520                  0.0             0.0

                    AGRCMCHN_ACDNT_OCRN_CNT  ...  BCYC_ACDNT_OCRN_CNT  \
OCRN_YMD   GRID_ID                           ...
2021-01-01 378508                       0.0  ...                  0.0
           378509                       0.0  ...                  0.0
           378510                       0.0  ...                  0.0
           378511                       0.0  ...                  0.0
           378512                       0.0  ...                  0.0
...                                     ...  ...                  ...
2021-12-30 417521                       0.0  ...                  0.0
           418517                       0.0  ...                  0.0
           418518                       0.0  ...                  0.0
           418519                       0.0  ...                  0.0
           418520                       0.0  ...                  0.0

                    ELTRC_ACDNT_OCRN_CNT  POSNG_OCRN_CNT  ASPHYXIA_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                    0.0             0.0                0.0
           378509                    0.0             0.0                0.0
           378510                    0.0             0.0                0.0
           378511                    0.0             0.0                0.0
           378512                    0.0             0.0                0.0
...                                  ...             ...                ...
2021-12-30 417521                    0.0             0.0                0.0
           418517                    0.0             0.0                0.0
           418518                    0.0             0.0                0.0
           418519                    0.0             0.0                0.0
           418520                    0.0             0.0                0.0

                    FALLING_OCRN_CNT  FLAME_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                0.0             0.0
           378509                0.0             0.0
           378510                0.0             0.0
           378511                0.0             0.0
           378512                0.0             0.0
...                              ...             ...
2021-12-30 417521                0.0             0.0
           418517                0.0             0.0
           418518                0.0             0.0
           418519                0.0             0.0
           418520                0.0             0.0

                    CHMC_SBSTNC_ACDNT_OCRN_CNT  WETHR_ACDNT_OCRN_CNT  \
OCRN_YMD   GRID_ID
2021-01-01 378508                          0.0                   0.0
           378509                          0.0                   0.0
           378510                          0.0                   0.0
           378511                          0.0                   0.0
           378512                          0.0                   0.0
...                                        ...                   ...
2021-12-30 417521                          0.0                   0.0
           418517                          0.0                   0.0
           418518                          0.0                   0.0
           418519                          0.0                   0.0
           418520                          0.0                   0.0

                    SXAL_ASALT_OCRN_CNT  BURN_OCRN_CNT
OCRN_YMD   GRID_ID
2021-01-01 378508                   0.0            0.0
           378509                   0.0            0.0
           378510                   0.0            0.0
           378511                   0.0            0.0
           378512                   0.0            0.0
...                                 ...            ...
2021-12-30 417521                   0.0            0.0
           418517                   0.0            0.0
           418518                   0.0            0.0
           418519                   0.0            0.0
           418520                   0.0            0.0

[302168 rows x 31 columns]

In [107]:
df4.groupby(['OCRN_YMD','GRID_ID']).sum().reset_index()

,OCRN_YMD,GRID_ID,HGTPOJ_ACDNT_OCRN_CNT,PNTRINJ_OCRN_CNT,MCHN_ACDNT_OCRN_CNT,ETC_OCRN_CNT,BLTRM_OCRN_CNT,ACDNT_INJ_OCRN_CNT,EXCL_DISEASE_OCRN_CNT,VHC_ACDNT_OCRN_CNT,...,BCYC_ACDNT_OCRN_CNT,ELTRC_ACDNT_OCRN_CNT,POSNG_OCRN_CNT,ASPHYXIA_OCRN_CNT,FALLING_OCRN_CNT,FLAME_OCRN_CNT,CHMC_SBSTNC_ACDNT_OCRN_CNT,WETHR_ACDNT_OCRN_CNT,SXAL_ASALT_OCRN_CNT,BURN_OCRN_CNT
0,2021-01-01,378508,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2021-01-01,378509,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2021-01-01,378510,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2021-01-01,378511,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2021-01-01,378512,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302163,2021-12-30,417521,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302164,2021-12-30,418517,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302165,2021-12-30,418518,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302166,2021-12-30,418519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302167,2021-12-30,418520,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
### Reshaping
## Pandas cheat sheet 참고

In [ ]:
### importing and exporting data

In [108]:
df = pd.read_csv ('02.dataset.csv', encoding = 'euc-kr')

In [109]:
df5 = df4.groupby(['OCRN_YMD','GRID_ID']).sum().reset_index()

In [111]:
df5.to_csv('groupby_YMD.csv',encoding = 'utf-8', index=False)